import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { CartProvider } from "@/context/CartContext";
import CartDisplay from "@/components/CartDisplay";
import SignupSection from "@/components/SignupSection";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Avion eCommerce",
  description: "Generated by Shoaib Munir",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
      </head>
      <body
        className={inter.className}
      >

        <CartProvider>
          <Navbar />
          <CartDisplay />
          {children}
          <SignupSection />
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
